ClientsLoans/urls.py
from django.urls import path
from ClientsLoans import views

app_name = 'clientsLoans'


urlpatterns = [

    path('clients', views.clients_list, name='clients'),
    path('addclient', views.clients_form, name='addclient'),
    path('delete/<int:id>', views.client_delete, name='client_delete'),
    path('addclient/<int:id>/',views.clients_form, name = 'client_update'),
]

libpanel/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usersApp.urls')),
    path('booksLoans/', include('booksLoans.urls')),
    path('clientsLoans/', include('ClientsLoans.urls')),
    path('loansApp/',include('loansApp.urls')),

]

ClientsLoans/models.py
from django.db import models

# Create your models here.

class clientsTable(models.Model):
    name = models.CharField(max_length=50)
    adress = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return '{}'.format(self.name)

ClientsLoans/forms.py
from django import forms
from .models import  clientsTable


class ClientsForm(forms.ModelForm):
     class Meta:
        model = clientsTable
        fields = '__all__'
        
        labels = {
            'name': 'Name',
            'adress': 'Adress',
            'phone': 'Phone',
            'mail': 'Email',
        }
        widgets= {
            'name':forms.TextInput(attrs = {'class':'form-control'}),
            'adress':forms.TextInput(attrs = {'class':'form-control'}),
            'phone':forms.TextInput(attrs = {'class':'form-control'}),
            'email':forms.TextInput(attrs = {'class':'form-control'}),
            
        }

ClientsLoans/views.py
from django.shortcuts import render,redirect
from .models import clientsTable
from libpanel import settings
from django.core.paginator import Paginator
# importamos forms
from .forms import ClientsForm
#para realizar consultar a la base de datos
from django.db.models import Q



# Create your views here.
        

# show clients
def clients_list(request):
    client_list = clientsTable.objects.all()
    queryset = request.GET.get('buscar')
    if queryset:
        client_list = clientsTable.objects.filter(
            Q(name__icontains= queryset) |
            Q(adress__icontains= queryset) |
            Q(email__icontains= queryset) |
            Q(phone__icontains= queryset) 

        ).distinct()
    return render(request,'clientsLoans/clients.html', {'list':client_list})    


# add and update clients
def clients_form(request,id=0):
    if request.method== "GET":
        if id == 0:
            form = ClientsForm()
        else:
           client = clientsTable.objects.get(pk=id)
           form = ClientsForm(instance=client)     
        return render(request,'clientsLoans/addclient.html',{'form':form})            
    else:
        if id == 0:
            form = ClientsForm(request.POST)
        else:
            book = clientsTable.objects.get(pk=id)
            form = ClientsForm(request.POST, instance= book)     
        if form.is_valid():
            form.save()             
        return redirect('/clientsLoans/clients')

# delete clients
def client_delete(request,id):
    client = clientsTable.objects.get(pk=id)
    client.delete()
    return redirect('/clientsLoans/clients')

ClientsLoans/templates/clientsLoans/addclient.html
{% extends 'usersApp/base.html' %}


{% block content %}


{% if user.is_authenticated %}

<div class="container">
    <div class="row" style="margin: 0 auto; background: rgb(130, 182, 130);padding: 50px;">
        <div class="col-6">
          <h3>Add a new Client</h3>  
        </div>
        <!-- form to add client -->
        <div class="col-6">
            <form action="" method="POST">
                {% csrf_token %}
                    {{ form.as_p}} 
                    <button type="submit" class="btn mr-5" style="background-color: rgb(149, 201, 149);">Add</button> 
                    <a href="{% url 'clientsLoans:clients' %}" class="btn btn-info" >Back</a>
            </form>
        </div>
    </div>
</div>

{% else %}

<h3>Login First Please</h3>

{% endif %}

{% endblock %}

ClientsLoans/templates/clientsLoans/clients.html
{% extends 'usersApp/base.html' %}


{% block content %}

{% if user.is_authenticated %}


<div class="row mt-3 ml-2 mr-2">
  <div class="container-lg col-8">
      <table class="table">
          <thead style="background-color: #e3f2fd;">
              <tr>
                <th>Name</th>
                <th>Adress</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Action</th>
              
              </tr>
          </thead>
          <tbody>
              <!-- list of clients -->
              {% for client in list %}
              <tr>
                <td> {{client.name}}</td>
                <td>{{client.adress}}</td>
                <td>{{client.phone}}</td>
                <td>{{client.email}}</td>
                <!-- buttons to update and delete -->
                  <td class="row">
                      <button class="btn  mr-1" style="background-color: rgb(233, 233, 10);">
                        <a href="{% url 'clientsLoans:client_update' client.id %}">
                          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                              <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                            </svg>
                        </a> 
                      </button>

                        <form action="{% url 'clientsLoans:client_delete' client.id %}" method="POST">
                            {%csrf_token%}
                          <button class="btn" style="background-color:rgb(230, 101, 101); " type="submit">
                              
                              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>

                          </button>
                      </form>                  
                  </td>
              </tr>
              {% endfor %}  
          </tbody>
      </table> 
  </div>

  <!-- right side -->
  <!-- add client -->
   <div class="container-lg col-4" >
      <a href="{% url 'clientsLoans:addclient' %}" class="btn"style="background-color: rgb(149, 201, 149);">Add a new Client</a>
      
      <hr>
      <!-- search client -->
   <div class="search mt-3" style= "background-color: rgb(229, 226, 226); padding: 10px;border-radius: 5px;">
          <form action="" method="GET">
              <div id="custom-search-input">
                  <p >Search a client by name,adress,phone or email</p><br>
                  <div class="input-group">
                      <input type="text" class="form-control" placeholder="search ..." name="buscar">
                      <button class="btn btn-success">
                          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                              <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                              <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                            </svg>
                      </button>
                  </div>
              </div>
          </form>
          <hr>
          <a href="{% url 'clientsLoans:clients' %}" class="btn btn-sm mt-3" style="background-color: rgb(82, 116, 38); color: white;">Show all the Clients</a>
    </div>

  </div>


</div>   

{% else %}

<h3>Login First Please</h3>

{% endif %}

{% endblock %}









<!-- 




<div class="row mt-3 ml-2 mr-2">
    <div class="container-lg col-8">
        <table class="table">
            <thead style="background-color: #e3f2fd;">
                <tr>
                    <th>Name</th>
                    <th>Adress</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Action</th>
                
                </tr>
            </thead>
            <tbody>
                {% for client in list%}
                <tr>
                    <td> {{client.name}}</td>
                    <td>{{client.adress}}</td>
                    <td>{{client.phone}}</td>
                    <td>{{client.email}}</td>
                    <td>
                        <button class="btn btn-sm" style="background-color: rgb(230, 101, 101);">Eliminar</button>
                        <button class="btn btn-sm" style="background-color: rgb(207, 207, 38);">editar</button>
                    </td>
                </tr>
                {% endfor %}  
            </tbody>  
        </table> 
    </div>  
</div>  -->
            <!-- {% if page_obj.has_previous or page_obj.has_next %}
        <nav class="mt-4">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% endif %}
                <li class="page-item disabled"><a class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %} -->

   