booksLoans/urls.py
from django.urls import path
from booksLoans import views


app_name = 'booksLoans'

urlpatterns = [
    path('books', views.books_list, name = 'books'),
    path('addbook', views.book_add, name='addbook'),
    path('delete/<int:id>', views.book_delete, name='book_delete'),
    path('addbook/<int:id>/',views.book_update, name = 'book_update'),
]

libpanel/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usersApp.urls')),
    path('booksLoans/', include('booksLoans.urls')),
    path('clientsLoans/', include('ClientsLoans.urls')),
    path('loansApp/',include('loansApp.urls')),

]

booksLoans/models.py
from django.db import models

# Create your models here.


class booksTable(models.Model):
    name = models.CharField(max_length=50)
    author = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.name)

# class clientsTable(models.Model):
#     name = models.CharField(max_length=50)
#     adress = models.CharField(max_length=50)
#     phone = models.CharField(max_length=50)
#     email = models.EmailField()

#     def __str__(self):s
#         return '{}'.format(self.name)

# class loansTable(models.Model):
#     bookLoan = models.OneToOneField(booksTable,null=True,blank=True,on_delete=models.CASCADE)
#     clientLoan = models.ForeignKey(clientsTable,null=True,blank=True,on_delete=models.CASCADE)
#     dateLoan = models.DateField()
#     dateReturn = models.DateField()
    

booksLoans/forms.py
from django import forms
from .models import booksTable
from loansApp.models import loansTable
 #clientsTable, loansTable

class BookForm(forms.ModelForm):
    # name = forms.CharField(widget = forms.TextInput(attrs={'class':'form-control', 'placeholder':'titulo'}))
    #  message = forms.CharField(widget = forms.Textarea(attrs={'class':'#add class name', 'placeholder':'If you require'}))
    class Meta:
        model = booksTable
        fields = ['name', 'author']
        
        labels = {
            'name': 'Titulo',
            'author': 'Autor'
        }
        widgets= {
            'name':forms.TextInput(attrs = {'class':'form-control'}),
            'author':forms.TextInput(attrs = {'class':'form-control'}),
            
        }




loan_status= [('borrowed','borrowed'),('returned','returned')]
class BookLoanForm(forms.ModelForm):
    class Meta():
        model = loansTable
        fields = ['bookLoan','clientLoan','dateLoan','dateReturn','status']
        labels={
            'bookLoan':'Book',
            'clientLoan':'Client',
            'dateLoan':'Date',
            'dateReturn':'Return',
            'status': 'Status',
        }
        widgets = {
            # 'bookLoan': forms.Select(attrs = {'class':'form-control'}),
            'clientLoan': forms.Select(attrs = {'class':'form-control'}),
            'dateLoan': forms.TextInput(attrs = {'class':'form-control','type':'date'}),
            'dateReturn': forms.TextInput(attrs = {'class':'form-control','type':'date'}),
            'status': forms.Select(choices=loan_status, attrs = {'class':'form-control'}),
        }




# class ClientsForm(forms.ModelForm):
#     class Meta:
#         model = clientsTable
#         fields = '__all__'
       


   
# class LoansForm(forms.ModelForm):
#     class Meta():
#         model = loansTable
#         fields = ['bookLoan','clientLoan','dateLoan','dateReturn']
#         labels={
#             'bookLoan':'Book',
#             'clientLoan':'Client',
#             'dateLoan':'Date',
#             'dateReturn':'Return',
#         }
#         widgets = {
#             'bookLoan': forms.Select(attrs = {'class':'form-control'}),
#             'clientLoan': forms.Select(attrs = {'class':'form-control'}),
#             'dateLoan': forms.TextInput(attrs = {'class':'form-control','type':'date'}),
#             'dateReturn': forms.TextInput(attrs = {'class':'form-control','type':'date'}),
#         }

booksLoans/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import booksTable
from loansApp.models import loansTable
from libpanel import settings
from .forms import BookForm,BookLoanForm
from django.db.models import Q


# Create your views here.


# show books
def books_list(request):
    books_list = booksTable.objects.all()
    queryset = request.GET.get('buscar')
    if queryset:
        books_list = booksTable.objects.filter(
            Q(name__icontains= queryset) |
            Q(author__icontains= queryset)
        ).distinct()
    return render(request,'booksLoans/books.html', {'list':books_list})    

# add books
def book_add(request):
    if request.method== "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()             
        return redirect('/booksLoans/books')
    else:     
         form= BookForm()         
    return render(request,'booksLoans/addbook.html',{'form':form})    

# update books
def book_update(request, id):
    book= booksTable.objects.get(id=id)
    form = BookForm
    if request.method == "POST":  
        form = BookForm(request.POST, instance=book)  
        if form.is_valid():
                form.save() 
        return redirect('/booksLoans/books')      
    else:
        form= BookForm(instance=book)
    return render(request,'booksLoans/addbook.html',{'form':form})  
    

# delete books
def book_delete(request,id):
    book = booksTable.objects.get(pk=id)
    book.delete()
    return redirect('/booksLoans/books')

booksLoans/templates/booksLoans/addbook.html
{% extends 'usersApp/base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}

<div class="container text-center" >
    <div class="row" style="margin: 0 auto; background: rgb(130, 182, 130);padding: 50px;">
        <div class="col-4">
          <h3>Books</h3>  
        </div>
        <!-- form to add book-->
        <div class="col-8">
            <form action="" method="POST">
                {% csrf_token %}
                    {{ form.as_p}} 
                    <button type="submit" class="btn mr-5" style="background-color: rgb(149, 201, 149);">Add</button> 
                    <a href="{% url 'booksLoans:books' %}" class="btn btn-info" >Back</a>
            </form>
        </div>
    </div>
</div>


{% else %}
<div class="container">
    <h3>Login First Please</h3>
</div>


{% endif %}

{% endblock %}

booksLoans/templates/booksLoans/books.html
{% extends 'usersApp/base.html' %}


{% block content %}


{% if user.is_authenticated %}

<div class="row mt-3 ml-2 mr-2">
    <div class="container-lg col-8">
        <table class="table">
            <thead style="background-color: #e3f2fd;">
                <tr>
                    <th>Libro</th>
                    <th>Autor</th>
                    <th>Accion</th>
                
                </tr>
            </thead>
            <tbody>
                <!-- show list of books -->
                {% for book in list %}
                <tr>
                    <td>{{book.name}}</td>
                    <td>{{book.author}}</td>
                    <td class="row">
                        <!-- update button -->
                        <button class="btn  mr-1" style="background-color: rgb(233, 233, 10);">
                          <a href="{% url 'booksLoans:book_update' book.id %}">

                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                              </svg>

                          </a> 
                        </button>
                        <!-- delete button -->
                          <form action="{% url 'booksLoans:book_delete' book.id %}" method="POST">
                              {%csrf_token%}
                            <button class="btn" style="background-color:rgb(230, 101, 101); " type="submit">
                                
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                  </svg>

                            </button>
                        </form>
                        
                    </td>
                </tr>
                {% endfor %}  
            </tbody>
        </table> 
    </div>

    <!-- right side -->
     <div class="container-lg col-4" >
       <a href="{% url 'booksLoans:addbook' %}"class="btn" style="background-color: rgb(149, 201, 149);"> Add a new Book</a>

        <hr>
        <!-- search book -->
        <div class="search mt-3" style= "background-color: rgb(229, 226, 226); padding: 10px;border-radius: 5px;">
            <form action="" method="GET">
                <div id="custom-search-input">
                    <p >Search a book by name or author</p><br>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="search ..." name="buscar">
                        <button class="btn btn-success">
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                                <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                              </svg>
                        </button>
                    </div>
                </div>
            </form>
            <hr>
            <a href="{% url 'booksLoans:books' %}" class="btn btn-sm mt-3" style="background-color: rgb(82, 116, 38); color: white;">Show all the Books</a>
        </div>
    </div>
</div>   

{% else %}

<h3>Login First Please</h3>

{% endif %}

 {% endblock %}