libpanel/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usersApp.urls')),
    path('booksLoans/', include('booksLoans.urls')),
    path('clientsLoans/', include('ClientsLoans.urls')),
    path('loansApp/',include('loansApp.urls')),

]

loansApp/urls.py
from django.urls import path
from loansApp import views 


app_name = 'loansApp'

urlpatterns = [
    path('loans', views.loans_list, name = 'loans'),
    path('addloan/', views.loan_add, name='addloan'),
    path('delete/<int:id>', views.loan_delete, name='loan_delete'),
    path('addloan/<int:id>/',views.loan_update, name = 'loan_update'),
]

loansApp/models.py
from django.db import models
from booksLoans.models import booksTable
from ClientsLoans.models import clientsTable

# Create your models here.

    


class loansTable(models.Model):
    bookLoan = models.OneToOneField(booksTable,null=True,blank=True,on_delete=models.CASCADE)
    clientLoan = models.ForeignKey(clientsTable,null=True,blank=True,on_delete=models.CASCADE)
    dateLoan = models.DateField()
    dateReturn = models.DateField()
    status = models.CharField(max_length=10,default='borrowed')

    def __str__(self):
        return '{}'.format(self.bookLoan,self.clientLoan,self.status)

loansApp/forms.py
from django import forms
from .models import loansTable



loan_status= [('borrowed','borrowed'),('returned','returned')]

class LoansForm(forms.ModelForm):
    class Meta():
        model = loansTable
        fields = ['bookLoan','clientLoan','dateLoan','dateReturn','status']
        labels={
            'bookLoan':'Book',
            'clientLoan':'Client',
            'dateLoan':'Date',
            'dateReturn':'Return',
            'status': 'Status',
        }
        widgets = {
            'bookLoan': forms.Select(attrs = {'class':'form-control'}),
            'clientLoan': forms.Select(attrs = {'class':'form-control'}),
            'dateLoan': forms.TextInput(attrs = {'class':'form-control','type':'date'}),
            'dateReturn': forms.TextInput(attrs = {'class':'form-control','type':'date'}),
            'status': forms.Select(choices=loan_status, attrs = {'class':'form-control'}),
        }

class LoansFormUpdate(forms.ModelForm):
    class Meta():
        model = loansTable
        fields = ['dateReturn','status']
        labels={
            'dateReturn':'Return',
            'status': 'Status',
        }
        widgets = {
            'dateReturn': forms.TextInput(attrs = {'class':'form-control','type':'date'}),
            'status': forms.Select(choices=loan_status, attrs = {'class':'form-control'}),
        }        

loansApp/views.py
from django.shortcuts import render,redirect
from django.urls import reverse, reverse_lazy
from libpanel import settings
from .models import loansTable
from .forms import LoansForm,LoansFormUpdate
from django.core.paginator import Paginator



# Create your views here.

# show loans
def loans_list(request):
    qs = loansTable.objects.all()
    paginator = Paginator(qs,5)
    page_number = request.GET.get('page',1)
    number_of_loans = len(qs)

    try:
        page_obj = paginator.page(page_number)
    except (PageNotAnInteger, EmptyPage):
        raise Http404(f'Invalid page {page_number}. That page contains no results')
    context = {'list':qs, 'object_list': page_obj,'page_obj': page_obj,'num':number_of_loans}

    return render(request, 'loansApp/loans.html',context)

# add loan
def loan_add(request):
    mensaje=''
    if request.method == 'POST':
        form= LoansForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/loansApp/loans')
        else:
            mensaje='the book is not available'     
    else:
        form= LoansForm()            
    return render (request,'loansApp/addloan.html',{'form':form,'mensaje':mensaje})   

# delete loan
def loan_delete(request,id):
    loan=loansTable.objects.get(pk=id)
    loan.delete()
    return redirect ('/loansApp/loans')


# update loan
def loan_update(request,id):
    loan = loansTable.objects.get(id=id)
    if request.method == 'GET':
        form = LoansFormUpdate(instance=loan)
        contexto = {
            'form':form
        }
    else:           
        loan = loansTable.objects.get(pk=id)
        form= LoansFormUpdate(request.POST,instance=loan)
        if form.is_valid():
            form.save()
        return redirect('/loansApp/loans')

    return render (request,'loansApp/addloan.html',contexto)   
 

loansApp/templates/loansApp/addloan.html
{% extends 'usersApp/base.html' %}

{% load static %}
{% block content %}
{% if user.is_authenticated %}

<div class="container text-center" >
    <div class="row" style="margin: 0 auto; background: rgb(130, 182, 130);padding: 50px;">
        <div class="col-4">
          <h3>Loans</h3> 
           <!--messege if the book was borrowed  -->
          <h4 class="mt-4" style="color: rgb(235, 59, 59);">{{mensaje}}</h4>
        </div>
        <!-- form to add a loan -->
        <div class="col-8">
            <form action="" method="POST">
                {% csrf_token %}
                    {{ form.as_p}} 
                    <button type="submit" class="btn mr-5" style="background-color: rgb(149, 201, 149);">Add</button> 
                    <a href="{% url 'loansApp:loans' %}" class="btn btn-info" >Back</a>
            </form>
        </div>
       
    </div>

        
        
    
</div>



{% else %}

<h3>Login First Please</h3>

{% endif %}
{% endblock %}

loansApp/templates/loansApp/loans.html
{% extends 'usersApp/base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="row mt-3 ml-2 mr-2">
    <div class="container-lg col-8">
        <table class="table" id="table">
            <thead style="background-color: #e3f2fd;">
                <tr>
                    <th>Book</th>
                    <th>Client</th>
                    <th>Date</th>
                    <th>Return</th>
                    <th>status</th>
                    <th>id</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <!-- list of loans -->
                {% for loan in object_list %}
                <tr id="tr">
                    <td> {{loan.bookLoan}}</td>
                    <td>{{loan.clientLoan}}</td> 
                    <td>{{loan.dateLoan}}</td>
                    <td>{{loan.dateReturn}}</td>
                    <td class="td" style="font-size: 16px; font-weight: 500;" >{{loan.status}}</td>
                    <td>{{loan.id}}</td>
                    <td class="row">
                       <!-- button to update  -->
                        <button class="btn  mr-1" style="background-color: rgb(233, 233, 10);">
                            <a href="{% url 'loansApp:loan_update' loan.id %}"> 
                              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                </svg>
                            </a> 
                          </button>
                          <!-- button to delete  -->
                        <form action="{% url 'loansApp:loan_delete' loan.id %}" method="POST">
                            {%csrf_token%}
                            <button class="btn" style="background-color:rgb(230, 101, 101); " type="submit"> 
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </button>   
                        </form>
                        
                    </td>
                </tr>
                {% endfor %}  

                <!-- pagination -->
                <tr>
                    <td>                       
                        {% if page_obj.has_previous or page_obj.has_next %}
                            <nav class="mt-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page=1">First</a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                                <span aria-hidden="true">&laquo;</span>
                                                <span class="sr-only">Previous</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                    <li class="page-item disabled"><a class="page-link">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                                <span aria-hidden="true">&raquo;</span>
                                                <span class="sr-only">Next</span>
                                            </a>
                                        </li>
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        {% endif %}
                    </td>
                </tr>
            </tbody>
        </table> 
    </div>

    <!-- right side -->
    <div class="container-lg col-4" >
        <a href="{% url 'loansApp:addloan' %}"class="btn" style="background-color: rgb(149, 201, 149);"> Add a new loan</a>

         <hr>

         <div>
             <h3>
                Number of books Borrowed: {{num}}
             </h3>
        </div>
    </div>

</div>
{% else %}

<h3>Login First Please</h3>

{% endif %}
{% endblock %}

    